### ISSUE TITLE
Support Placeholder

### ISSUE THREAD

**Issue by iAziz786** [ashleyw/react-sane-contenteditable#47]
I was thinking of adding support for placeholder because they provide more visual feedback what the rendered component is about (e.g. Typing message, Write a comment, etc.).

One way, and probably the easiest way I have found is using `:empty:before` pseudo CSS class. But the problem with that is we have to manage an extra CSS file just to get this right. Until now, CSS is absent from this project.

I'm here getting some ideas from maintainers what they thought would be the best thing to do?

**Comment by nijk** [comment]
@iAziz786 I think it's great that you're looking for ways to improve this lib and I certainly don't want to discourage debate on what this lib should do. 

That said, what you're proposing feels rather niche and I believe it could be implemented just as easily by a React project that imports this dependency. I'm not sure that I see the value of this addition to the lib at this stage.

**Comment by iAziz786** [comment]
Thanks, @nijk for your feedback. I have searched and tried many content-editable components and can't find anyone which matches the simplicity and effectiveness of this library. So yes, it's true that I want to see improvements to this.

Me too don't want to make this simple and light library bulky. That's why I have started this issue to ask guidance about how to add support for the feature in an effective manner while keeping its innocence.

The reason why I think placeholder is the integral of this library because most of the places where this library is going to be used are places, where they might want their users to type something. I certainly use it the places where I want my users to type something. Now, you are right when you said users can implement their own placeholder; I can't debate whether it's easy for them or not because it might depend on their implementation.

You'll find that almost every place where users have to type some data into some type of form element will have a way to add placeholder (e.g. input, textarea), then why it should be left out from content-editable elements? Having it natively in the library will definitely help the users, notably, if the user is a new developer, they can use the library without any hassle of knowing how to add support for one.

Curious to know your thoughts :thought_balloon:

**Comment by nijk** [comment]
Whilst not all React projects are identical, there are many commonalities when invoking 3rd party react components. After all this is a simple lib that can only be used in a very small number of ways - see the tests of you don't believe me...

I think the best way to progress this is for you to provide a demo React project implementation with placeholder functionality being provided by the project rather than this lib. This will give you an indication of the required complexity and ultimately the necessity of this feature request; if the implementation is impossible then I think that would be a good justification for this feature request.

If the implementation is not so straight-forward or has a lot of boilerplate then it might be better handled via documentation or example code in the lib.

**Comment by iAziz786** [comment]
This is what I came up with. I'm only using CSS to implement this. I tried doing this with JS only but ended up having a lot of bugs.

[Link](https://codesandbox.io/s/rw3zkklr54)

**Comment by nijk** [comment]
Nice! That's super simple as well, which means it's almost certainly the best option. I think we could add a styling section to the Readme so that we're spelling out how to achieve this use case. Would you like to raise a PR for documentation?

**Comment by iAziz786** [comment]
Yes! I'll raise a PR soon.

**Comment by iAziz786** [comment]
Didn't get the chance to work on this, therefore closing it.
