### ISSUE TITLE
Breaking change in 1.6.0

### ISSUE THREAD

**Issue by ahutchings** [ashleyw/react-sane-contenteditable#63]
In 1.6.0, the `onChange` prop is called with `onChange(value)`. Prior to this version it was called with `onChange(event, value)`.

My use cases for this library don't need the event, but this change does break existing code reading the value from the 2nd parameter position. I have a library which depends on ^1.5.0, so a user of the library will soon install 1.6 and experience the issue.

Per the SemVer FAQ, the thing to do in this case is to [publish a new minor version restoring the previous behavior](https://semver.org/#what-do-i-do-if-i-accidentally-release-a-backwards-incompatible-change-as-a-minor-version). That will ensure that anyone depending on `^1` won't run into this change. You may also want to deprecate 1.6.0. If the change to the `onChange` is intentional and still desired, it could then be released as 2.0.0.

Thank you in advance for your prompt attention. It's only been a few hours since 1.6 was released so I'm hoping this can be rectified before users run into this. Please let me know if I can do anything to assist with the process!

**Comment by ashleyw** [comment]
Hi @ahutchings,

Thanks for the report — that is definitely a breaking change!

Fixed in [`1.6.1`](https://www.npmjs.com/package/react-sane-contenteditable/v/1.6.1) (https://github.com/ashleyw/react-sane-contenteditable/commit/9e409818d3ab95323267b091274b94a06a0cab2d), and as-per your recommendation, `1.6.0` has been deprecated.

Sorry for the inconvenience. This was entirely my mistake.

**Comment by ahutchings** [comment]
No worries. Thanks for the fast turnaround!
